### 历史各OJ刷题量
## 2018.3

<table align="center">
  <tr>
    <td>班级</td>
    <td>姓名</td>
    <td>CF ID</td>
    <td>Uva</td>
    <td>HDU</td>
    <td>POJ</td>
    <td>Codeforces</td>
  </tr>
  <tr>
    <td>软工161</td>
    <td>李昊洋</td>
    <td>thirtiseven</td>
    <td>10</td>
    <td>42</td>
    <td>14</td>
    <td>226</td>
  </tr>
  <tr>
    <td>计嵌162</td>
    <td>王淦</td>
    <td>wanggann</td>
    <td></td>
    <td>12</td>
    <td></td>
    <td>264</td>
  </tr>
  <tr>
    <td>物联网171</td>
    <td>赵静珂 </td>
    <td>_Simon_</td>
    <td></td>
    <td>22</td>
    <td>3</td>
    <td>15</td>
  </tr>
  <tr>
    <td>网工161</td>
    <td>侯承忻</td>
    <td>sijidou</td>
    <td></td>
    <td></td>
    <td></td>
    <td>8</td>
  </tr>
  <tr>
    <td>网工161</td>
    <td>邱晨阳</td>
    <td>taitesi</td>
    <td></td>
    <td></td>
    <td></td>
    <td>5</td>
  </tr>
  <tr>
    <td>交通运输171z</td>
    <td>叶冬冬</td>
    <td>excaliburEx</td>
    <td>1</td>
    <td></td>
    <td>1</td>
    <td>7</td>
  </tr>
  <tr>
    <td>计嵌172</td>
    <td>葛骅</td>
    <td>K.GH</td>
    <td></td>
    <td></td>
    <td></td>
    <td>1</td>
  </tr>
  <tr>
    <td>软嵌171</td>
    <td>陈虎</td>
    <td>xyfillusion</td>
    <td></td>
    <td></td>
    <td></td>
    <td>2</td>
  </tr>
  <tr>
    <td>网工172</td>
    <td>郁越</td>
    <td>Cathy98</td>
    <td></td>
    <td></td>
    <td></td>
    <td>2</td>
  </tr>
  <tr>
    <td>软工171</td>
    <td>赵海洲</td>
    <td>chenzhao</td>
    <td></td>
    <td></td>
    <td></td>
    <td>2</td>
  </tr>
  <tr>
    <td>网工171z</td>
    <td>张宸易</td>
    <td>index2014</td>
    <td></td>
    <td></td>
    <td></td>
    <td>7</td>
  </tr>
  <tr>
    <td>计嵌172</td>
    <td>杜剑雄</td>
    <td>Endlesscs</td>
    <td></td>
    <td></td>
    <td></td>
    <td>4</td>
  </tr>
  <tr>
    <td></td>
  </tr>
  <tr>
    <td></td>
  </tr>
</table>
